# Generated by Django 5.2.7 on 2025-11-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='libros_cuentas/')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual'), ('EVENTO', 'Evento Específico')], default='MENSUAL', max_length=20)),
                ('fecha_periodo', models.DateField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_periodo'],
            },
        ),
    ]
