# Generated by Django 5.2.7 on 2025-11-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_librocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor_tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('TESORERO', 'Tesorero')], max_length=10)),
                ('destinatario_tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('TESORERO', 'Tesorero')], max_length=10)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='mensajes_adjuntos/')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
