# Generated by Django 5.2.7 on 2025-12-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha_donacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='nombre_donador',
            field=models.CharField(default='Anónimo', max_length=255),
        ),
    ]
