# Generated by Django 5.2.7 on 2025-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donador', models.CharField(default='Anónimo', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Preferencia MP')),
                ('pago_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Pago MP')),
                ('estado', models.CharField(default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('fecha_donacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
