# Generated by Django 5.2.7 on 2025-12-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contacto'),
        ('api', '0005_alter_donacion_fecha_donacion_and_more'),
    ]

    operations = [
    ]
