# Generated by Django 5.2.7 on 2025-12-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20251204_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
