# Generated by Django 5.2.7 on 2025-12-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_solicitudingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('REUNION', 'Reunión'), ('EVENTO', 'Evento público'), ('VOLUNTARIADO', 'Voluntariado'), ('CAPACITACION', 'Capacitación'), ('RECAUDACION', 'Recaudación de fondos'), ('ADMINISTRATIVO', 'Administrativo')], default='REUNION', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
