# Generated by Django 5.2.7 on 2025-12-06 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eventocalendario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudingreso',
            name='usuario_activo',
            field=models.BooleanField(default=False, verbose_name='¿Usuario activo?'),
        ),
        migrations.AddField(
            model_name='solicitudingreso',
            name='usuario_creado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_ingreso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django creado'),
        ),
    ]
