# Generated by Django 5.2.7 on 2025-12-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_solicitudingreso_usuario_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudingreso',
            name='password_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
