# Generated by Django 5.2.7 on 2025-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_solicitudingreso_password_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudingreso',
            name='password_generada',
            field=models.CharField(blank=True, help_text='Contraseña generada al aprobar (se muestra solo una vez)', max_length=100, null=True, verbose_name='Contraseña generada'),
        ),
    ]
