# Generated by Django 5.2.7 on 2025-12-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_solicitudingreso_password_generada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudingreso',
            name='password_temporal',
        ),
        migrations.AlterField(
            model_name='solicitudingreso',
            name='password_generada',
            field=models.CharField(blank=True, help_text='Contraseña generada al aprobar la solicitud', max_length=100, null=True, verbose_name='Contraseña generada'),
        ),
    ]
