# Generated by Django 5.2.7 on 2025-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_solicitudingreso_password_temporal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/'),
        ),
    ]
