# Generated by Django 5.2.7 on 2025-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_solicitudingreso_password_temporal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudingreso',
            name='divisa',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar Americano')], default='CLP', max_length=3),
        ),
    ]
