# Generated by Django 5.2.7 on 2025-12-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_solicitudingreso_divisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudingreso',
            name='divisa',
        ),
    ]
