# Generated by Django 5.2.7 on 2025-12-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_anuncio_imagen'),
        ('api', '0015_remove_solicitudingreso_divisa'),
    ]

    operations = [
    ]
